productTypeQuantity: {
    orderChangeDate: '2025-01-20 10:18:12',
    receivedDate: '',
    payments: {
      orderPaymentDays: 0,
      orderPaymentType: 'cash_on_delivery',
      orderRebatePercent: 10,
      orderWorthCalculateType: 'gross',
      orderVatExists: 'y',
      orderCurrency: {
        currencyId: 'PLN',
        orderCurrencyValue: 1,
        billingCurrencyRate: 1,
        orderProductsCost: 1981.26,
        orderDeliveryCost: 0,
        orderPayformCost: 0,
        orderInsuranceCost: 0
      },
      orderBaseCurrency: {
        orderProductsCost: 1981.26,
        orderDeliveryCost: 0,
        orderDeliveryVat: 23,
        orderPayformCost: 0,
        orderPayformVat: 0,
        orderInsuranceCost: 0,
        orderInsuranceVat: 0,
        billingCurrency: 'PLN'
      }
    },
    dispatch: {
      courierWebserviceOnly: false,
      deliveryWeight: 6000,
      courierName: 'DHL Paczka - standard',
      courierId: 100097,
      deliveryPackageId: '',
      deliveryDate: '2025-01-10',
      estimatedDeliveryDate: '2025-01-03 23:38:00',
      deliveryDateAdditional: '10:00 - 12:00'
    },
    prepaids: [],
    purchaseDate: '2025-01-03',
    subscriptionId: 0,
    orderStatus: 'on_order',
    orderOperatorLogin: '',
    orderPackingPersonLogin: null,
    apiFlag: 'none',
    orderConfirmation: 'none',
    orderAddDate: '2025-01-03 13:38:58',
    orderDispatchDate: 0,
    orderPrepareTime: 0,
    clientNoteToOrder: 'no dzialaj no ty',
    clientNoteToCourier: 'testowanmie plosze',
    orderNote: '',
    stockId: 1,
    clientRequestInvoice: 'e_invoice',
    clientDeliveryAddressId: 16172,
    productRemovedInStock: 'y',
    orderSourceResults: {
      preorderSourcesDetails: [ [Object] ],
      orderSourceType: 'shop',
      shopId: 1,
      auctionsServiceName: '',
      orderSourceDetails: {
        fresh: 'n',
        fulfillment: 'n',
        sourcePageUrl: 'https://zooart6.yourtechnicaldomain.com/panel/main.php',
        orderSourceName: 'Wejście bezpośrednie',
        orderSourceTypeId: 1,
        orderSourceType: 'shop',
        orderSourceId: 1,
        orderExternalId: null
      }
    },
    auctionInfo: {},
    productsResults: [
      {
        productOrderPriceBaseCurrency: 145.08,
        productOrderPriceNetBaseCurrency: 134.33,
        productOrderAdditional: '<bundled>eac6621b8d8c995671b2f0c81324855d</bundled>',
        basketPosition: 0,
        productPriceLog: '',
        productId: 4147,
        productName: 'lol XD',
        productCode: 'AN-83207',
        sizeId: 'uniw',
        sizePanelName: 'uniw',
        productSizeCodeExternal: '',
        stockId: 1,
        productQuantity: 2,
        productWeight: 1000,
        productVat: 8,
        productPanelPrice: 145.08,
        productPanelPriceNet: 134.33,
        remarksToProduct: '',
        productSerialNumbers: null,
        bundleId: 17059,
        productOrderPrice: 145.08,
        productOrderPriceNet: 134.33,
        orderSalesMode: 'money'
      },
      {
        productOrderPriceBaseCurrency: 1691.1,
        productOrderPriceNetBaseCurrency: 1374.88,
        productOrderAdditional: '',
        basketPosition: 1,
        productPriceLog: '<ul><li>Początkowa cena brutto: detaliczna 1879.00zł, hurtowa: 0.00zł, minimalna: 0.00zł</li><li>Początkowa cena netto: detaliczna 1527.64zł, hurtowa: 0.00zł, minimalna: 0.00zł</li><li>Stawka VAT: 23.0%</li><li>Waluta klienta: PLN, waluta produktu: PLN</li><li>Cena brutto dla sklepu detaliczna: 1879.00zł, hurtowa: 0.00zł, minimalna: 0.00zł</li><li>Zakup dokonany po cenach detalicznych</li><li>Rabat z zamówienia 10.00% (towar dodany po złożeniu zamówienia)</li><li>Suma rabatów jest większa od najwyższego rabatu nie sumowanego. Przyznany rabat do produktu: 10.00%</li><li>Wartość pozycji wynosi: 1691.10zł, ilość: 1</li><li>Wartość pozycji w walucie klienta brutto: 1691.10zł, netto: 1374.88zł</li><li>Cena jednostkowa w walucie klienta brutto: 1691.10zł, netto: 1374.88zł</li></ul>',
        productId: 123100,
        productName: 'KONAMI stół, blat - czarny marmur, nogi - złoty (2p=1szt)',
        productCode: '',
        sizeId: 'uniw',
        sizePanelName: 'uniw',
        productSizeCodeExternal: 'zooart6_23243-0',
        stockId: 0,
        productQuantity: 1,
        productWeight: 0,
        productVat: 23,
        productPanelPrice: 1691.1,
        productPanelPriceNet: 1374.88,
        remarksToProduct: '',
        productSerialNumbers: null,
        bundleId: 0,
        productOrderPrice: 1691.1,
        productOrderPriceNet: 1374.88,
        orderSalesMode: 'money'
      }
    ],
    dropshippingOrderStatus: 'none'
  }